### ISSUE TITLE
Could you make an english bot too?

### ISSUE THREAD

**Issue by Fyzick5** [Dabsunter/sparklin-exploder#1]
Heres the full dictionary of bombparty https://pastebin.com/raw/K54aJ5ez

**Comment by Dabsunter** [comment]
There are already some forks that have been updated with an English dictionary:
- [imthe666st/sparklin-exploder](https://github.com/imthe666st/sparklin-exploder)
- [Beatbox309/sparklin-exploder](https://github.com/Beatbox309/sparklin-exploder)

You could do so yourself:
1. Fork the repo, so that you will be able to edit any file you want
2. Create a new `dictionary.js` with the following content
```js
var words = ["aa","aah","aahed", ... ,"zzzs"]
```
3. Update the `dictionary.js` on your repository, and your own version will be automatically aviable at  http://fyzick5.github.io/sparklin-exploder/exploder.js !

Of course there is too many words to do it manually, but here is the challenge 😉 
You can do it with a little Python script, or even with Notepad++ macros

Have fun !

**Comment by Fyzick5** [comment]
Ok, thank you!
